# Generated by Django 5.0 on 2024-01-31 12:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DRAFT', 'DRAFT'), ('INACTIVE', 'Inactive'), ('REMOVED', 'Removed')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('same_city_matches', models.JSONField(blank=True, default=dict, null=True)),
                ('different_city_matches', models.JSONField(blank=True, default=dict, null=True)),
                ('recruitment_status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In_Progress'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('RECRUITED', 'Recruited'), ('ON_HOLD', 'On_Hold')], default='PENDING', max_length=30)),
                ('open_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to='recruitment.openjobs')),
            ],
            options={
                'verbose_name_plural': 'Job Match Profile',
            },
        ),
    ]
