# Generated by Django 5.0 on 2024-01-24 16:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DRAFT', 'DRAFT'), ('INACTIVE', 'Inactive'), ('REMOVED', 'Removed')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=150)),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=150)),
                ('city', models.CharField(blank=True, choices=[('BAGERHAT', 'Bagerhat'), ('BAKHTEYARPUR', 'Bakhteyarpur'), ('BANDARBAN', 'Bandarban'), ('BARGUNA', 'Barguna'), ('BARISHAL', 'Barishal'), ('BHOLA', 'Bhola'), ('BOGRA', 'Bogra'), ('CHANDPUR', 'Chandpur'), ('CHAPAINAWABGANJ', 'Chapainawabganj'), ('CHHAGALNAIYA', 'Chhagalnaiya'), ('CHITTAGONG', 'Chittagong'), ('CHITTAGONG_PORT', 'Chittagong Port'), ('CHUADANGA', 'Chuadanga'), ('COX_S_BAZAR', "Cox's Bazar"), ('COMILLA', 'Comilla'), ('FARIDPUR', 'Faridpur'), ('FENI', 'Feni'), ('GAZIPUR', 'Gazipur'), ('GOPALGANJ', 'Gopalganj'), ('HABIGANJ', 'Habiganj'), ('JESSORE', 'Jessore'), ('JHALOKATHI', 'Jhalokathi'), ('JHENIDAH', 'Jhenidah'), ('JOYPURHAT', 'Joypurhat'), ('KALIGANJ', 'Kaliganj'), ('KERANIGANJ', 'Keraniganj'), ('KHAGRACHARI', 'Khagrachari'), ('KISHOREGANJ', 'Kishoreganj'), ('KISHORGANJ', 'Kishorganj'), ('KHULNA', 'Khulna'), ('KUAKATA', 'Kuakata'), ('KURIGRAM', 'Kurigram'), ('KUSHTIA', 'Kushtia'), ('LAKSHMIPUR', 'Lakshmipur'), ('LALMONIRHAT', 'Lalmonirhat'), ('MAGURA', 'Magura'), ('MAULVI_BAZAR', 'Maulvi Bazar'), ('MADARIPUR', 'Madaripur'), ('MOHESHKHALI', 'Moheshkhali'), ('MYMENSINGH', 'Mymensingh'), ('NARAIL', 'Narail'), ('NARAYANGANJ', 'Narayanganj'), ('NARSINGDI', 'Narsingdi'), ('NARSHINGDI', 'Narshingdi'), ('NATORE', 'Natore'), ('NAOGAON', 'Naogaon'), ('NAWABGANJ', 'Nawabganj'), ('NILPHAMARI', 'Nilphamari'), ('PATUAKHALI', 'Patuakhali'), ('PABNA', 'Pabna'), ('PAIKGACHHA', 'Paikgachha'), ('PANCHAGARH', 'Panchagarh'), ('PARBATIPUR', 'Parbatipur'), ('PUTHIA', 'Puthia'), ('RAJBARI', 'Rajbari'), ('RAIPUR', 'Raipur'), ('RAJSHAHI', 'Rajshahi'), ('RANGPUR', 'Rangpur'), ('SARISHA', 'Sarisha'), ('SATKHIRA', 'Satkhira'), ('SABAIL', 'Sabail'), ('SANDWIP', 'Sandwip'), ('SHARANKHALI', 'Sharankhali'), ('SHYAMNAGAR', 'Shyamnagar'), ('SIRAJGANJ', 'Sirajganj'), ('SITAKUNDA', 'Sitakunda'), ('SUNAMGANJ', 'Sunamganj'), ('SYLHET', 'Sylhet'), ('TANGAIL', 'Tangail'), ('THAKURGAON', 'Thakurgaon'), ('TUNGIPARA', 'Tungipara'), ('ULLAHPARA', 'Ullahpara'), ('UNKNOWN', 'Unknown')], db_index=True, default='UNKNOWN', max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('UNKNOWN', 'Unknown'), ('OTHER', 'Other')], default='UNKNOWN', max_length=20)),
                ('dob', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'DIVORCED'), ('OTHER', 'Other')], default='OTHER', max_length=100)),
                ('telephone', models.CharField(blank=True, db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('profession_desires', models.CharField(blank=True, max_length=255)),
                ('profile_state', models.CharField(blank=True, max_length=100)),
                ('recruitment_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In_Progress'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('RECRUITED', 'Recruited'), ('ON_HOLD', 'On_Hold')], default='PENDING', max_length=100)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('original_cv', models.FileField(blank=True, null=True, upload_to='original_cvs')),
                ('cv_raw', models.TextField(blank=True, null=True)),
                ('skills', models.JSONField(blank=True, default=dict)),
                ('commercial_level', models.CharField(blank=True, max_length=100)),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('job_request', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
